apiVersion: v1
kind: Namespace
metadata:
  name: default
---
apiVersion: v1
kind: Secret
metadata:
  namespace: default
  name: example-provider-secret
type: Opaque
stringData:
  # A Personal Access Token (PAT) generated for the Azure DevOps
  # organization referenced below. Grant it only the scopes required by
  # the resources you intend to manage.
  credentials: REPLACE_ME_WITH_YOUR_PAT
---
apiVersion: azuredevops.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: example
  namespace: default
spec:
  organizationUrl: https://dev.azure.com/example-org
  credentials:
    source: Secret
    secretRef:
      namespace: default
      name: example-provider-secret
      key: credentials
---
apiVersion: azuredevops.crossplane.io/v1alpha1
kind: ClusterProviderConfig
metadata:
  name: example
spec:
  organizationUrl: https://dev.azure.com/example-org
  credentials:
    source: Secret
    secretRef:
      namespace: default
      name: example-provider-secret
      key: credentials
