// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	v1alpha11 "github.com/dunkin0486/provider-azuredevops/apis/gitrepository/v1alpha1"
	v1alpha1 "github.com/dunkin0486/provider-azuredevops/apis/project/v1alpha1"
	v1alpha12 "github.com/dunkin0486/provider-azuredevops/apis/variablegroup/v1alpha1"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this BuildDefinition.
func (mg *BuildDefinition) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var mrsp reference.MultiNamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: mg.Spec.ForProvider.ProjectID,
		Extract:      v1alpha1.ProjectID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ProjectIDRef,
		Selector:     mg.Spec.ForProvider.ProjectIDSelector,
		To: reference.To{
			List:    &v1alpha1.ProjectList{},
			Managed: &v1alpha1.Project{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ProjectID")
	}
	mg.Spec.ForProvider.ProjectID = rsp.ResolvedValue
	mg.Spec.ForProvider.ProjectIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: mg.Spec.ForProvider.RepositoryID,
		Extract:      v1alpha11.GitRepositoryID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.RepositoryIDRef,
		Selector:     mg.Spec.ForProvider.RepositoryIDSelector,
		To: reference.To{
			List:    &v1alpha11.GitRepositoryList{},
			Managed: &v1alpha11.GitRepository{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.RepositoryID")
	}
	mg.Spec.ForProvider.RepositoryID = rsp.ResolvedValue
	mg.Spec.ForProvider.RepositoryIDRef = rsp.ResolvedReference

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
		CurrentValues: mg.Spec.ForProvider.VariableGroupIDs,
		Extract:       v1alpha12.VariableGroupID(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.ForProvider.VariableGroupIDRefs,
		Selector:      mg.Spec.ForProvider.VariableGroupIDSelector,
		To: reference.To{
			List:    &v1alpha12.VariableGroupList{},
			Managed: &v1alpha12.VariableGroup{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.VariableGroupIDs")
	}
	mg.Spec.ForProvider.VariableGroupIDs = mrsp.ResolvedValues
	mg.Spec.ForProvider.VariableGroupIDRefs = mrsp.ResolvedReferences

	return nil
}
