//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane/apis/v2/core/v2"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BranchPolicyWorkItemLinking) DeepCopyInto(out *BranchPolicyWorkItemLinking) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BranchPolicyWorkItemLinking.
func (in *BranchPolicyWorkItemLinking) DeepCopy() *BranchPolicyWorkItemLinking {
	if in == nil {
		return nil
	}
	out := new(BranchPolicyWorkItemLinking)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BranchPolicyWorkItemLinking) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BranchPolicyWorkItemLinkingList) DeepCopyInto(out *BranchPolicyWorkItemLinkingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BranchPolicyWorkItemLinking, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BranchPolicyWorkItemLinkingList.
func (in *BranchPolicyWorkItemLinkingList) DeepCopy() *BranchPolicyWorkItemLinkingList {
	if in == nil {
		return nil
	}
	out := new(BranchPolicyWorkItemLinkingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BranchPolicyWorkItemLinkingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BranchPolicyWorkItemLinkingObservation) DeepCopyInto(out *BranchPolicyWorkItemLinkingObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BranchPolicyWorkItemLinkingObservation.
func (in *BranchPolicyWorkItemLinkingObservation) DeepCopy() *BranchPolicyWorkItemLinkingObservation {
	if in == nil {
		return nil
	}
	out := new(BranchPolicyWorkItemLinkingObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BranchPolicyWorkItemLinkingParameters) DeepCopyInto(out *BranchPolicyWorkItemLinkingParameters) {
	*out = *in
	if in.ProjectIDRef != nil {
		in, out := &in.ProjectIDRef, &out.ProjectIDRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.ProjectIDSelector != nil {
		in, out := &in.ProjectIDSelector, &out.ProjectIDSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.RepositoryIDRef != nil {
		in, out := &in.RepositoryIDRef, &out.RepositoryIDRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.RepositoryIDSelector != nil {
		in, out := &in.RepositoryIDSelector, &out.RepositoryIDSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BranchPolicyWorkItemLinkingParameters.
func (in *BranchPolicyWorkItemLinkingParameters) DeepCopy() *BranchPolicyWorkItemLinkingParameters {
	if in == nil {
		return nil
	}
	out := new(BranchPolicyWorkItemLinkingParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BranchPolicyWorkItemLinkingSpec) DeepCopyInto(out *BranchPolicyWorkItemLinkingSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BranchPolicyWorkItemLinkingSpec.
func (in *BranchPolicyWorkItemLinkingSpec) DeepCopy() *BranchPolicyWorkItemLinkingSpec {
	if in == nil {
		return nil
	}
	out := new(BranchPolicyWorkItemLinkingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BranchPolicyWorkItemLinkingStatus) DeepCopyInto(out *BranchPolicyWorkItemLinkingStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BranchPolicyWorkItemLinkingStatus.
func (in *BranchPolicyWorkItemLinkingStatus) DeepCopy() *BranchPolicyWorkItemLinkingStatus {
	if in == nil {
		return nil
	}
	out := new(BranchPolicyWorkItemLinkingStatus)
	in.DeepCopyInto(out)
	return out
}
