//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane/apis/v2/core/v2"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BranchPolicyBuildValidation) DeepCopyInto(out *BranchPolicyBuildValidation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BranchPolicyBuildValidation.
func (in *BranchPolicyBuildValidation) DeepCopy() *BranchPolicyBuildValidation {
	if in == nil {
		return nil
	}
	out := new(BranchPolicyBuildValidation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BranchPolicyBuildValidation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BranchPolicyBuildValidationList) DeepCopyInto(out *BranchPolicyBuildValidationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BranchPolicyBuildValidation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BranchPolicyBuildValidationList.
func (in *BranchPolicyBuildValidationList) DeepCopy() *BranchPolicyBuildValidationList {
	if in == nil {
		return nil
	}
	out := new(BranchPolicyBuildValidationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BranchPolicyBuildValidationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BranchPolicyBuildValidationObservation) DeepCopyInto(out *BranchPolicyBuildValidationObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BranchPolicyBuildValidationObservation.
func (in *BranchPolicyBuildValidationObservation) DeepCopy() *BranchPolicyBuildValidationObservation {
	if in == nil {
		return nil
	}
	out := new(BranchPolicyBuildValidationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BranchPolicyBuildValidationParameters) DeepCopyInto(out *BranchPolicyBuildValidationParameters) {
	*out = *in
	if in.ProjectIDRef != nil {
		in, out := &in.ProjectIDRef, &out.ProjectIDRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.ProjectIDSelector != nil {
		in, out := &in.ProjectIDSelector, &out.ProjectIDSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.RepositoryIDRef != nil {
		in, out := &in.RepositoryIDRef, &out.RepositoryIDRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.RepositoryIDSelector != nil {
		in, out := &in.RepositoryIDSelector, &out.RepositoryIDSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.BuildDefinitionIDRef != nil {
		in, out := &in.BuildDefinitionIDRef, &out.BuildDefinitionIDRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.BuildDefinitionIDSelector != nil {
		in, out := &in.BuildDefinitionIDSelector, &out.BuildDefinitionIDSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BranchPolicyBuildValidationParameters.
func (in *BranchPolicyBuildValidationParameters) DeepCopy() *BranchPolicyBuildValidationParameters {
	if in == nil {
		return nil
	}
	out := new(BranchPolicyBuildValidationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BranchPolicyBuildValidationSpec) DeepCopyInto(out *BranchPolicyBuildValidationSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BranchPolicyBuildValidationSpec.
func (in *BranchPolicyBuildValidationSpec) DeepCopy() *BranchPolicyBuildValidationSpec {
	if in == nil {
		return nil
	}
	out := new(BranchPolicyBuildValidationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BranchPolicyBuildValidationStatus) DeepCopyInto(out *BranchPolicyBuildValidationStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BranchPolicyBuildValidationStatus.
func (in *BranchPolicyBuildValidationStatus) DeepCopy() *BranchPolicyBuildValidationStatus {
	if in == nil {
		return nil
	}
	out := new(BranchPolicyBuildValidationStatus)
	in.DeepCopyInto(out)
	return out
}
