//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane/apis/v2/core/v2"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BranchPolicyMinReviewers) DeepCopyInto(out *BranchPolicyMinReviewers) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BranchPolicyMinReviewers.
func (in *BranchPolicyMinReviewers) DeepCopy() *BranchPolicyMinReviewers {
	if in == nil {
		return nil
	}
	out := new(BranchPolicyMinReviewers)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BranchPolicyMinReviewers) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BranchPolicyMinReviewersList) DeepCopyInto(out *BranchPolicyMinReviewersList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BranchPolicyMinReviewers, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BranchPolicyMinReviewersList.
func (in *BranchPolicyMinReviewersList) DeepCopy() *BranchPolicyMinReviewersList {
	if in == nil {
		return nil
	}
	out := new(BranchPolicyMinReviewersList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BranchPolicyMinReviewersList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BranchPolicyMinReviewersObservation) DeepCopyInto(out *BranchPolicyMinReviewersObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BranchPolicyMinReviewersObservation.
func (in *BranchPolicyMinReviewersObservation) DeepCopy() *BranchPolicyMinReviewersObservation {
	if in == nil {
		return nil
	}
	out := new(BranchPolicyMinReviewersObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BranchPolicyMinReviewersParameters) DeepCopyInto(out *BranchPolicyMinReviewersParameters) {
	*out = *in
	if in.ProjectIDRef != nil {
		in, out := &in.ProjectIDRef, &out.ProjectIDRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.ProjectIDSelector != nil {
		in, out := &in.ProjectIDSelector, &out.ProjectIDSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.RepositoryIDRef != nil {
		in, out := &in.RepositoryIDRef, &out.RepositoryIDRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.RepositoryIDSelector != nil {
		in, out := &in.RepositoryIDSelector, &out.RepositoryIDSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BranchPolicyMinReviewersParameters.
func (in *BranchPolicyMinReviewersParameters) DeepCopy() *BranchPolicyMinReviewersParameters {
	if in == nil {
		return nil
	}
	out := new(BranchPolicyMinReviewersParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BranchPolicyMinReviewersSpec) DeepCopyInto(out *BranchPolicyMinReviewersSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BranchPolicyMinReviewersSpec.
func (in *BranchPolicyMinReviewersSpec) DeepCopy() *BranchPolicyMinReviewersSpec {
	if in == nil {
		return nil
	}
	out := new(BranchPolicyMinReviewersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BranchPolicyMinReviewersStatus) DeepCopyInto(out *BranchPolicyMinReviewersStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BranchPolicyMinReviewersStatus.
func (in *BranchPolicyMinReviewersStatus) DeepCopy() *BranchPolicyMinReviewersStatus {
	if in == nil {
		return nil
	}
	out := new(BranchPolicyMinReviewersStatus)
	in.DeepCopyInto(out)
	return out
}
