//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectEntitlementParameters) DeepCopyInto(out *ProjectEntitlementParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectEntitlementParameters.
func (in *ProjectEntitlementParameters) DeepCopy() *ProjectEntitlementParameters {
	if in == nil {
		return nil
	}
	out := new(ProjectEntitlementParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserEntitlement) DeepCopyInto(out *UserEntitlement) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserEntitlement.
func (in *UserEntitlement) DeepCopy() *UserEntitlement {
	if in == nil {
		return nil
	}
	out := new(UserEntitlement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UserEntitlement) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserEntitlementList) DeepCopyInto(out *UserEntitlementList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UserEntitlement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserEntitlementList.
func (in *UserEntitlementList) DeepCopy() *UserEntitlementList {
	if in == nil {
		return nil
	}
	out := new(UserEntitlementList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UserEntitlementList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserEntitlementObservation) DeepCopyInto(out *UserEntitlementObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserEntitlementObservation.
func (in *UserEntitlementObservation) DeepCopy() *UserEntitlementObservation {
	if in == nil {
		return nil
	}
	out := new(UserEntitlementObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserEntitlementParameters) DeepCopyInto(out *UserEntitlementParameters) {
	*out = *in
	if in.ProjectEntitlements != nil {
		in, out := &in.ProjectEntitlements, &out.ProjectEntitlements
		*out = make([]ProjectEntitlementParameters, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserEntitlementParameters.
func (in *UserEntitlementParameters) DeepCopy() *UserEntitlementParameters {
	if in == nil {
		return nil
	}
	out := new(UserEntitlementParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserEntitlementSpec) DeepCopyInto(out *UserEntitlementSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserEntitlementSpec.
func (in *UserEntitlementSpec) DeepCopy() *UserEntitlementSpec {
	if in == nil {
		return nil
	}
	out := new(UserEntitlementSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserEntitlementStatus) DeepCopyInto(out *UserEntitlementStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserEntitlementStatus.
func (in *UserEntitlementStatus) DeepCopy() *UserEntitlementStatus {
	if in == nil {
		return nil
	}
	out := new(UserEntitlementStatus)
	in.DeepCopyInto(out)
	return out
}
