// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	v1alpha1 "github.com/dunkin0486/provider-azuredevops/apis/group/v1alpha1"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this GroupMembership.
func (mg *GroupMembership) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: mg.Spec.ForProvider.GroupDescriptor,
		Extract:      GroupDescriptor(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.GroupDescriptorRef,
		Selector:     mg.Spec.ForProvider.GroupDescriptorSelector,
		To: reference.To{
			List:    &v1alpha1.GroupList{},
			Managed: &v1alpha1.Group{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.GroupDescriptor")
	}
	mg.Spec.ForProvider.GroupDescriptor = rsp.ResolvedValue
	mg.Spec.ForProvider.GroupDescriptorRef = rsp.ResolvedReference

	return nil
}
