apiVersion: groupmembership.azuredevops.crossplane.io/v1alpha1
kind: GroupMembership
metadata:
  name: example-groupmembership
  namespace: default
spec:
  providerConfigRef:
    name: example
  forProvider:
    # Graph descriptors come from Azure DevOps graph subject/group lookups
    # (for example the Graph Users, Groups, or Teams APIs).
    memberDescriptor: aadgp.Uy0xLTktMTU1MTM3NDI0My0xMjM0NTY3ODkwLTEyMzQ1Njc4OS0xMjM0NTY3ODkwLTEyMzQ1Njc4OTAtMS0xMjM0NTY3ODktMQ
    groupDescriptorRef:
      name: example-group
    mode: add
