//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane/apis/v2/core/v2"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceEndpointKubernetes) DeepCopyInto(out *ServiceEndpointKubernetes) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceEndpointKubernetes.
func (in *ServiceEndpointKubernetes) DeepCopy() *ServiceEndpointKubernetes {
	if in == nil {
		return nil
	}
	out := new(ServiceEndpointKubernetes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceEndpointKubernetes) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceEndpointKubernetesList) DeepCopyInto(out *ServiceEndpointKubernetesList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ServiceEndpointKubernetes, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceEndpointKubernetesList.
func (in *ServiceEndpointKubernetesList) DeepCopy() *ServiceEndpointKubernetesList {
	if in == nil {
		return nil
	}
	out := new(ServiceEndpointKubernetesList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceEndpointKubernetesList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceEndpointKubernetesObservation) DeepCopyInto(out *ServiceEndpointKubernetesObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceEndpointKubernetesObservation.
func (in *ServiceEndpointKubernetesObservation) DeepCopy() *ServiceEndpointKubernetesObservation {
	if in == nil {
		return nil
	}
	out := new(ServiceEndpointKubernetesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceEndpointKubernetesParameters) DeepCopyInto(out *ServiceEndpointKubernetesParameters) {
	*out = *in
	if in.ProjectIDRef != nil {
		in, out := &in.ProjectIDRef, &out.ProjectIDRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.ProjectIDSelector != nil {
		in, out := &in.ProjectIDSelector, &out.ProjectIDSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.KubeconfigSecretRef != nil {
		in, out := &in.KubeconfigSecretRef, &out.KubeconfigSecretRef
		*out = new(v2.SecretKeySelector)
		**out = **in
	}
	if in.ServiceAccountTokenSecretRef != nil {
		in, out := &in.ServiceAccountTokenSecretRef, &out.ServiceAccountTokenSecretRef
		*out = new(v2.SecretKeySelector)
		**out = **in
	}
	if in.AzureSubscriptionRef != nil {
		in, out := &in.AzureSubscriptionRef, &out.AzureSubscriptionRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceEndpointKubernetesParameters.
func (in *ServiceEndpointKubernetesParameters) DeepCopy() *ServiceEndpointKubernetesParameters {
	if in == nil {
		return nil
	}
	out := new(ServiceEndpointKubernetesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceEndpointKubernetesSpec) DeepCopyInto(out *ServiceEndpointKubernetesSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceEndpointKubernetesSpec.
func (in *ServiceEndpointKubernetesSpec) DeepCopy() *ServiceEndpointKubernetesSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceEndpointKubernetesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceEndpointKubernetesStatus) DeepCopyInto(out *ServiceEndpointKubernetesStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceEndpointKubernetesStatus.
func (in *ServiceEndpointKubernetesStatus) DeepCopy() *ServiceEndpointKubernetesStatus {
	if in == nil {
		return nil
	}
	out := new(ServiceEndpointKubernetesStatus)
	in.DeepCopyInto(out)
	return out
}
