//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane/apis/v2/core/v2"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BranchPolicyCommentResolution) DeepCopyInto(out *BranchPolicyCommentResolution) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BranchPolicyCommentResolution.
func (in *BranchPolicyCommentResolution) DeepCopy() *BranchPolicyCommentResolution {
	if in == nil {
		return nil
	}
	out := new(BranchPolicyCommentResolution)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BranchPolicyCommentResolution) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BranchPolicyCommentResolutionList) DeepCopyInto(out *BranchPolicyCommentResolutionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BranchPolicyCommentResolution, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BranchPolicyCommentResolutionList.
func (in *BranchPolicyCommentResolutionList) DeepCopy() *BranchPolicyCommentResolutionList {
	if in == nil {
		return nil
	}
	out := new(BranchPolicyCommentResolutionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BranchPolicyCommentResolutionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BranchPolicyCommentResolutionObservation) DeepCopyInto(out *BranchPolicyCommentResolutionObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BranchPolicyCommentResolutionObservation.
func (in *BranchPolicyCommentResolutionObservation) DeepCopy() *BranchPolicyCommentResolutionObservation {
	if in == nil {
		return nil
	}
	out := new(BranchPolicyCommentResolutionObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BranchPolicyCommentResolutionParameters) DeepCopyInto(out *BranchPolicyCommentResolutionParameters) {
	*out = *in
	if in.ProjectIDRef != nil {
		in, out := &in.ProjectIDRef, &out.ProjectIDRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.ProjectIDSelector != nil {
		in, out := &in.ProjectIDSelector, &out.ProjectIDSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.RepositoryIDRef != nil {
		in, out := &in.RepositoryIDRef, &out.RepositoryIDRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.RepositoryIDSelector != nil {
		in, out := &in.RepositoryIDSelector, &out.RepositoryIDSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BranchPolicyCommentResolutionParameters.
func (in *BranchPolicyCommentResolutionParameters) DeepCopy() *BranchPolicyCommentResolutionParameters {
	if in == nil {
		return nil
	}
	out := new(BranchPolicyCommentResolutionParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BranchPolicyCommentResolutionSpec) DeepCopyInto(out *BranchPolicyCommentResolutionSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BranchPolicyCommentResolutionSpec.
func (in *BranchPolicyCommentResolutionSpec) DeepCopy() *BranchPolicyCommentResolutionSpec {
	if in == nil {
		return nil
	}
	out := new(BranchPolicyCommentResolutionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BranchPolicyCommentResolutionStatus) DeepCopyInto(out *BranchPolicyCommentResolutionStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BranchPolicyCommentResolutionStatus.
func (in *BranchPolicyCommentResolutionStatus) DeepCopy() *BranchPolicyCommentResolutionStatus {
	if in == nil {
		return nil
	}
	out := new(BranchPolicyCommentResolutionStatus)
	in.DeepCopyInto(out)
	return out
}
