//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane/apis/v2/core/v2"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceEndpointDockerRegistry) DeepCopyInto(out *ServiceEndpointDockerRegistry) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceEndpointDockerRegistry.
func (in *ServiceEndpointDockerRegistry) DeepCopy() *ServiceEndpointDockerRegistry {
	if in == nil {
		return nil
	}
	out := new(ServiceEndpointDockerRegistry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceEndpointDockerRegistry) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceEndpointDockerRegistryList) DeepCopyInto(out *ServiceEndpointDockerRegistryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ServiceEndpointDockerRegistry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceEndpointDockerRegistryList.
func (in *ServiceEndpointDockerRegistryList) DeepCopy() *ServiceEndpointDockerRegistryList {
	if in == nil {
		return nil
	}
	out := new(ServiceEndpointDockerRegistryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceEndpointDockerRegistryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceEndpointDockerRegistryObservation) DeepCopyInto(out *ServiceEndpointDockerRegistryObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceEndpointDockerRegistryObservation.
func (in *ServiceEndpointDockerRegistryObservation) DeepCopy() *ServiceEndpointDockerRegistryObservation {
	if in == nil {
		return nil
	}
	out := new(ServiceEndpointDockerRegistryObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceEndpointDockerRegistryParameters) DeepCopyInto(out *ServiceEndpointDockerRegistryParameters) {
	*out = *in
	if in.ProjectIDRef != nil {
		in, out := &in.ProjectIDRef, &out.ProjectIDRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.ProjectIDSelector != nil {
		in, out := &in.ProjectIDSelector, &out.ProjectIDSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.UsernameSecretRef != nil {
		in, out := &in.UsernameSecretRef, &out.UsernameSecretRef
		*out = new(v2.SecretKeySelector)
		**out = **in
	}
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(v2.SecretKeySelector)
		**out = **in
	}
	if in.AzureSubscriptionRef != nil {
		in, out := &in.AzureSubscriptionRef, &out.AzureSubscriptionRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceEndpointDockerRegistryParameters.
func (in *ServiceEndpointDockerRegistryParameters) DeepCopy() *ServiceEndpointDockerRegistryParameters {
	if in == nil {
		return nil
	}
	out := new(ServiceEndpointDockerRegistryParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceEndpointDockerRegistrySpec) DeepCopyInto(out *ServiceEndpointDockerRegistrySpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceEndpointDockerRegistrySpec.
func (in *ServiceEndpointDockerRegistrySpec) DeepCopy() *ServiceEndpointDockerRegistrySpec {
	if in == nil {
		return nil
	}
	out := new(ServiceEndpointDockerRegistrySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceEndpointDockerRegistryStatus) DeepCopyInto(out *ServiceEndpointDockerRegistryStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceEndpointDockerRegistryStatus.
func (in *ServiceEndpointDockerRegistryStatus) DeepCopy() *ServiceEndpointDockerRegistryStatus {
	if in == nil {
		return nil
	}
	out := new(ServiceEndpointDockerRegistryStatus)
	in.DeepCopyInto(out)
	return out
}
