apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Provider
metadata:
  name: provider-azuredevops
  annotations:
    meta.crossplane.io/maintainer: dunkin0486 <https://github.com/dunkin0486>
    meta.crossplane.io/source: github.com/dunkin0486/provider-azuredevops
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      A Crossplane provider for managing Azure DevOps resources.
spec:
  capabilities:
    - safe-start
