//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane/apis/v2/core/v2"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceEndpointAzureRM) DeepCopyInto(out *ServiceEndpointAzureRM) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceEndpointAzureRM.
func (in *ServiceEndpointAzureRM) DeepCopy() *ServiceEndpointAzureRM {
	if in == nil {
		return nil
	}
	out := new(ServiceEndpointAzureRM)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceEndpointAzureRM) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceEndpointAzureRMCredentials) DeepCopyInto(out *ServiceEndpointAzureRMCredentials) {
	*out = *in
	if in.ServicePrincipal != nil {
		in, out := &in.ServicePrincipal, &out.ServicePrincipal
		*out = new(ServicePrincipalCredentials)
		**out = **in
	}
	if in.WorkloadIdentityFederation != nil {
		in, out := &in.WorkloadIdentityFederation, &out.WorkloadIdentityFederation
		*out = new(WorkloadIdentityFederationCredentials)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceEndpointAzureRMCredentials.
func (in *ServiceEndpointAzureRMCredentials) DeepCopy() *ServiceEndpointAzureRMCredentials {
	if in == nil {
		return nil
	}
	out := new(ServiceEndpointAzureRMCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceEndpointAzureRMList) DeepCopyInto(out *ServiceEndpointAzureRMList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ServiceEndpointAzureRM, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceEndpointAzureRMList.
func (in *ServiceEndpointAzureRMList) DeepCopy() *ServiceEndpointAzureRMList {
	if in == nil {
		return nil
	}
	out := new(ServiceEndpointAzureRMList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceEndpointAzureRMList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceEndpointAzureRMObservation) DeepCopyInto(out *ServiceEndpointAzureRMObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceEndpointAzureRMObservation.
func (in *ServiceEndpointAzureRMObservation) DeepCopy() *ServiceEndpointAzureRMObservation {
	if in == nil {
		return nil
	}
	out := new(ServiceEndpointAzureRMObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceEndpointAzureRMParameters) DeepCopyInto(out *ServiceEndpointAzureRMParameters) {
	*out = *in
	if in.ProjectIDRef != nil {
		in, out := &in.ProjectIDRef, &out.ProjectIDRef
		*out = new(v2.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.ProjectIDSelector != nil {
		in, out := &in.ProjectIDSelector, &out.ProjectIDSelector
		*out = new(v2.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	in.Credentials.DeepCopyInto(&out.Credentials)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceEndpointAzureRMParameters.
func (in *ServiceEndpointAzureRMParameters) DeepCopy() *ServiceEndpointAzureRMParameters {
	if in == nil {
		return nil
	}
	out := new(ServiceEndpointAzureRMParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceEndpointAzureRMSpec) DeepCopyInto(out *ServiceEndpointAzureRMSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceEndpointAzureRMSpec.
func (in *ServiceEndpointAzureRMSpec) DeepCopy() *ServiceEndpointAzureRMSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceEndpointAzureRMSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceEndpointAzureRMStatus) DeepCopyInto(out *ServiceEndpointAzureRMStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceEndpointAzureRMStatus.
func (in *ServiceEndpointAzureRMStatus) DeepCopy() *ServiceEndpointAzureRMStatus {
	if in == nil {
		return nil
	}
	out := new(ServiceEndpointAzureRMStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServicePrincipalCredentials) DeepCopyInto(out *ServicePrincipalCredentials) {
	*out = *in
	out.ClientSecretRef = in.ClientSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServicePrincipalCredentials.
func (in *ServicePrincipalCredentials) DeepCopy() *ServicePrincipalCredentials {
	if in == nil {
		return nil
	}
	out := new(ServicePrincipalCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadIdentityFederationCredentials) DeepCopyInto(out *WorkloadIdentityFederationCredentials) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadIdentityFederationCredentials.
func (in *WorkloadIdentityFederationCredentials) DeepCopy() *WorkloadIdentityFederationCredentials {
	if in == nil {
		return nil
	}
	out := new(WorkloadIdentityFederationCredentials)
	in.DeepCopyInto(out)
	return out
}
